import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { ensureRbac } from './rbac-definitions';

const prisma = new PrismaClient();

async function main() {
  const organisation = await prisma.organisation.upsert({ where: { slug: 'safe-nest' }, update: {}, create: { id: 'org-safe-nest', name: 'Safe Nest Housing & Support', slug: 'safe-nest', timezone: 'Europe/London' } });
  const { roles } = await ensureRbac(prisma, organisation.id);
  const passwordHash = await bcrypt.hash('ChangeMe!123', 12);
  const admin = await prisma.user.upsert({ where: { email: 'admin@safenest.test' }, update: {}, create: { id: 'user-admin', organisationId: organisation.id, email: 'admin@safenest.test', name: 'Development admin', jobTitle: 'Organisation administrator', passwordHash, mfaRequired: false } });
  await prisma.membership.upsert({ where: { organisationId_userId_roleId: { organisationId: organisation.id, userId: admin.id, roleId: roles.get('organisation-administrator')! } }, update: {}, create: { organisationId: organisation.id, userId: admin.id, roleId: roles.get('organisation-administrator')! } });
  const supportLead = await prisma.user.upsert({ where: { email: 'j.whitfield@safenest.test' }, update: {}, create: { id: 'user-support-lead', organisationId: organisation.id, email: 'j.whitfield@safenest.test', name: 'J. Whitfield', jobTitle: 'Support lead', passwordHash } });
  await prisma.membership.upsert({ where: { organisationId_userId_roleId: { organisationId: organisation.id, userId: supportLead.id, roleId: roles.get('support-lead')! } }, update: {}, create: { organisationId: organisation.id, userId: supportLead.id, roleId: roles.get('support-lead')! } });

  const serviceDefinitions = [
    ['svc-supported', 'Supported accommodation', 'supported-accommodation', 'A safe, settled home with practical support around you.'],
    ['svc-homelessness', 'Homelessness support', 'homelessness-support', 'A route from crisis to a home that lasts.'],
    ['svc-care', 'Care leavers and young people', 'care-leavers', 'A steady start for young adults making their own way.'],
    ['svc-abuse', 'Domestic abuse', 'domestic-abuse', 'Confidential refuge and support, without judgement.'],
    ['svc-mental', 'Mental health', 'mental-health', 'A calm base for recovery and everyday wellbeing.'],
    ['svc-refugee', 'Refugee move-on', 'refugee-move-on', 'A welcoming home while a new chapter takes shape.']
  ] as const;
  const services = new Map<string, string>();
  for (const [id, title, slug, summary] of serviceDefinitions) { const service = await prisma.service.upsert({ where: { organisationId_slug: { organisationId: organisation.id, slug } }, update: { title, summary }, create: { id, organisationId: organisation.id, title, slug, summary, content: summary, audience: 'People who need a safe place and practical support.', referralRoutes: 'Professional and self-referrals welcome.', eligibility: 'We will discuss eligibility and availability with you.', supportModel: 'Person-led support with planned reviews.', displayOrder: services.size } }); services.set(slug, service.id); }
  const propertyDefinitions = [
    ['prop-willow', 'Willow House', 'willow-house', 'Northside', 'Domestic abuse', 6, '2 rooms available', true, services.get('domestic-abuse')!],
    ['prop-harbour', 'Harbour Court', 'harbour-court', 'Riverside', 'Young people', 8, '1 room available', false, services.get('care-leavers')!],
    ['prop-fenwick', 'Fenwick Road', 'fenwick-road', 'Eastfield', 'Mental health', 4, 'Full — waitlist', false, services.get('mental-health')!],
    ['prop-alder', 'Alder Terrace', 'alder-terrace', 'Westgate', 'Homelessness support', 10, '3 rooms available', false, services.get('homelessness-support')!],
    ['prop-linden', 'Linden Place', 'linden-place', 'Old Town', 'Refugee move-on', 5, 'Family flat available', false, services.get('refugee-move-on')!]
  ] as const;
  const properties = new Map<string, string>();
  for (const [id, publicName, slug, neighbourhood, serviceType, capacity, vacancy, confidential, serviceId] of propertyDefinitions) { const property = await prisma.property.upsert({ where: { organisationId_slug: { organisationId: organisation.id, slug } }, update: { publicVacancyState: vacancy }, create: { id, organisationId: organisation.id, serviceId, publicName, slug, neighbourhood, serviceType, publicSummary: `A welcoming Safe Nest home in ${neighbourhood}.`, facilities: JSON.stringify(['Secure entry', 'Shared kitchen', 'Key work']), eligibility: 'Discussed during referral assessment.', capacity, publicVacancyState: vacancy, accessibility: 'Ask the team about individual access needs.', confidential, secureAddress: confidential ? 'Stored privately — never publish' : `${neighbourhood}, your town`, displayOrder: properties.size } }); properties.set(slug, property.id); }
  const roomDefinitions = [['room-alder-1', properties.get('alder-terrace')!, 'Room 1', 'OCCUPIED'], ['room-alder-2', properties.get('alder-terrace')!, 'Room 2', 'AVAILABLE'], ['room-alder-3', properties.get('alder-terrace')!, 'Room 3', 'OCCUPIED'], ['room-harbour-1', properties.get('harbour-court')!, 'Flat 1', 'AVAILABLE'], ['room-harbour-2', properties.get('harbour-court')!, 'Flat 2', 'OCCUPIED'], ['room-fenwick-1', properties.get('fenwick-road')!, 'Room 1', 'OCCUPIED'], ['room-willow-1', properties.get('willow-house')!, 'Room 1', 'AVAILABLE']] as const;
  for (const [id, propertyId, label, status] of roomDefinitions) await prisma.room.upsert({ where: { propertyId_label: { propertyId, label } }, update: { status }, create: { id, propertyId, label, status } });

  const categoryDefinitions = [['cat-announcements', 'Announcements', 'announcements'], ['cat-stories', 'Stories', 'stories'], ['cat-reports', 'Reports', 'reports'], ['cat-community', 'Community', 'community'], ['cat-policy', 'Policy', 'policy']] as const;
  const categories = new Map<string, string>();
  for (const [id, name, slug] of categoryDefinitions) { const category = await prisma.newsCategory.upsert({ where: { organisationId_slug: { organisationId: organisation.id, slug } }, update: { name }, create: { id, organisationId: organisation.id, name, slug } }); categories.set(slug, category.id); }
  const posts = [['post-houses', 'Two new houses open in Westgate, adding twelve supported rooms', 'new-houses-westgate', 'A partnership with the city council brings our first Housing First-model homes online this summer.', 'announcements', '2026-06-12'], ['post-leah', '“I got my daughter back” — Leah’s year at Willow House', 'leahs-year-at-willow-house', 'A resident’s own account of refuge, recovery and reunion. Shared with permission.', 'stories', '2026-05-16'], ['post-report', 'Our 2025–26 outcomes report is out', 'outcomes-report-2025-26', '94% of residents sustained their move-on tenancy at six months.', 'reports', '2026-05-02'], ['post-gardeners', 'Volunteer gardeners wanted for three of our houses', 'volunteer-gardeners-wanted', 'Green-fingered? Our residents are building kitchen gardens this summer.', 'community', '2026-04-20'], ['post-policy', 'What the Renters’ Rights changes mean for our residents', 'renters-rights-explainer', 'A plain-English explainer from our housing team.', 'policy', '2026-03-04']] as const;
  for (const [id, title, slug, summary, category, date] of posts) await prisma.newsPost.upsert({ where: { organisationId_slug: { organisationId: organisation.id, slug } }, update: { title, summary, published: true }, create: { id, organisationId: organisation.id, categoryId: categories.get(category)!, title, slug, summary, content: summary, authorName: 'Safe Nest team', published: true, publishedAt: new Date(date) } });
  const settingValues = [['homepage.headline', 'A safe place to land. The support to move on.'], ['homepage.stats.moveOn', '94%'], ['homepage.stats.newRooms', '12'], ['homepage.stats.responseTarget', '7 days'], ['contact.generalEmail', 'hello@safenest.example'], ['contact.referralEmail', 'referrals@safenest.example'], ['contact.emergencyMessage', 'In immediate danger, call 999. For confidential support, call 0800 000 0000.']];
  for (const [key, value] of settingValues) await prisma.siteSetting.upsert({ where: { organisationId_key: { organisationId: organisation.id, key } }, update: { value }, create: { organisationId: organisation.id, key, value } });
  const clientOne = await prisma.client.upsert({ where: { reference: 'SN-C-001' }, update: {}, create: { id: 'client-one', organisationId: organisation.id, serviceId: services.get('homelessness-support'), reference: 'SN-C-001', displayName: 'Amelia Morgan', riskLevel: 'Medium', status: 'CURRENT' } });
  const clientTwo = await prisma.client.upsert({ where: { reference: 'SN-C-002' }, update: {}, create: { id: 'client-two', organisationId: organisation.id, serviceId: services.get('mental-health'), reference: 'SN-C-002', displayName: 'Rafi Khan', riskLevel: 'Low', status: 'CURRENT' } });
  const clientThree = await prisma.client.upsert({ where: { reference: 'SN-C-003' }, update: {}, create: { id: 'client-three', organisationId: organisation.id, serviceId: services.get('care-leavers'), reference: 'SN-C-003', displayName: 'Sofia Taylor', riskLevel: 'High', restricted: true, status: 'WAITLIST' } });
  const roomAlder = await prisma.room.findFirstOrThrow({ where: { id: 'room-alder-1' } });
  const placement = await prisma.placement.upsert({ where: { id: 'placement-one' }, update: {}, create: { id: 'placement-one', clientId: clientOne.id, propertyId: properties.get('alder-terrace')!, roomId: roomAlder.id, startDate: new Date('2026-05-01'), status: 'ACTIVE' } });
  await prisma.supportPlan.upsert({ where: { id: 'plan-one' }, update: {}, create: { id: 'plan-one', clientId: clientOne.id, createdBy: supportLead.id, reviewDate: new Date('2026-07-28'), goals: { create: [{ category: 'Housing', desiredOutcome: 'Maintain a safe, stable tenancy', actionSteps: 'Weekly budgeting and tenancy check-in', status: 'IN_PROGRESS' }, { category: 'Wellbeing', desiredOutcome: 'Reconnect with community support', actionSteps: 'Attend one local group each month', status: 'ON_TRACK' }] } } });
  await prisma.caseNote.upsert({ where: { id: 'note-one' }, update: {}, create: { id: 'note-one', clientId: clientOne.id, authorId: supportLead.id, contactType: 'Key work session', category: 'Housing', note: 'Fictional development note. Resident reviewed next tenancy steps.', outcome: 'Agreed follow-up.', finalised: true } });
  await prisma.incident.upsert({ where: { reference: 'INC-2607-018' }, update: {}, create: { organisationId: organisation.id, clientId: clientThree.id, reference: 'INC-2607-018', category: 'Welfare concern', severity: 'High', status: 'UNDER_REVIEW', incidentAt: new Date('2026-07-17'), description: 'Fictional seed incident for development testing.', assignedLeadId: supportLead.id, restricted: true } });
  await prisma.task.upsert({ where: { id: 'task-seed-one' }, update: {}, create: { id: 'task-seed-one', organisationId: organisation.id, title: 'Call back Northside referral', description: 'Confirm assessment availability.', priority: 'HIGH', status: 'OPEN', dueAt: new Date('2026-07-18'), assignedToId: supportLead.id, clientId: clientOne.id } });
  await prisma.housingBenefitClaim.upsert({ where: { id: 'hb-one' }, update: {}, create: { id: 'hb-one', clientId: clientOne.id, status: 'IN_PAYMENT', paymentStatus: 'IN_PAYMENT', weeklyRentMinor: 18500, serviceChargeMinor: 2500 } });
  await prisma.referral.upsert({ where: { reference: 'SN-2607-001' }, update: {}, create: { id: 'ref-seed-one', organisationId: organisation.id, serviceId: services.get('homelessness-support')!, reference: 'SN-2607-001', status: 'TRIAGE', referrerName: 'J. Whitfield', referrerOrganisation: 'City Housing Options', referrerEmail: 'j.whitfield@safenest.test', personName: 'A. Morgan', currentLocation: 'Temporary accommodation', housingSituation: 'Fictional seed referral for development testing.', supportNeeds: 'Housing and tenancy support.', consentGiven: true, privacyAcknowledged: true, statusHistory: { create: { next: 'NEW', reason: 'Development seed' } } } });
  await prisma.referral.upsert({ where: { reference: 'SN-2607-002' }, update: {}, create: { id: 'ref-seed-two', organisationId: organisation.id, serviceId: services.get('mental-health')!, reference: 'SN-2607-002', status: 'ASSESSMENT_BOOKED', referrerName: 'M. Green', referrerOrganisation: 'Community Mental Health Team', referrerEmail: 'm.green@safenest.test', personName: 'R. Khan', currentLocation: 'Hospital discharge pathway', housingSituation: 'Fictional seed referral for development testing.', supportNeeds: 'Step-down support.', consentGiven: true, privacyAcknowledged: true, statusHistory: { create: { next: 'NEW', reason: 'Development seed' } } } });
  console.log('Seeded fictional Safe Nest development data. Login: admin@safenest.test / ChangeMe!123');
}

main().catch((error) => { console.error(error); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
