import type { Metadata } from 'next';
import { ButtonLink, getPropertyVisual, PublicPageHero, SectionHeading } from '@/components/PublicUI';
import { Icon } from '@/components/Icons';
import Image from 'next/image';

export const metadata: Metadata = { title: 'About Safe Nest', description: 'A housing and support organisation built around safety, dignity, and what comes next.' };

export default function AboutPage() {
  return <main>
    <PublicPageHero eyebrow="About Safe Nest" title="A home is more than four walls." intro="It is the starting point for safety, confidence, and a life that feels like your own." image={getPropertyVisual('Refugee move-on')} />
    <section className="section"><div className="container content-grid"><div className="prose"><SectionHeading eyebrow="Who we are" title="Practical support. Human first." /><p>Safe Nest is a housing and support organisation. We provide welcoming homes and steady, person-led support for people moving through difficult circumstances.</p><p>We believe that safety comes before everything else. From there, the right support can help someone make choices, build routines, reconnect with people they love, and move towards a home of their own.</p><ButtonLink href="/services">See our services <Icon name="arrow" size={15} /></ButtonLink></div><div className="principle-list"><div className="principle"><h3>Safety first</h3><p>Every interaction begins with safety, confidentiality, and a clear plan for what happens next.</p></div><div className="principle"><h3>Person-led support</h3><p>People know their own lives. We listen carefully and build support around their goals, strengths, and communication needs.</p></div><div className="principle"><h3>No wrong door</h3><p>If we are not the right service, we will help you find the right one. Asking for help should never be a dead end.</p></div></div></div></section>
    <section className="section image-story"><div className="container image-story-grid"><div className="image-story-photo"><Image src="/images/new-kitchen-support.jpg" alt="Two people talking together in a welcoming kitchen" fill sizes="(max-width: 1000px) 100vw, 50vw" /></div><div className="prose"><SectionHeading eyebrow="Support in practice" title="Small steps, taken together." /><p>Sometimes the most important support is a calm conversation, a practical plan, and someone who keeps showing up. We make space for people to set the pace and define what a good next chapter looks like.</p></div></div></section>
    <section className="section section-tint"><div className="container"><SectionHeading eyebrow="Our people" title="A team that stays curious." intro="Our staff bring experience in housing, support work, safeguarding, and community partnerships. We work across disciplines and keep learning." /><div className="service-grid"><div className="info-card"><h3>Quality and accountability</h3><p>We use supervision, reflective practice, resident feedback, and outcome reporting to keep improving the service people experience.</p></div><div className="info-card"><h3>Working with partners</h3><p>We work with local authorities, health teams, voluntary organisations, landlords, and residents to make support feel joined up.</p></div><div className="info-card"><h3>Our organisation</h3><p>Safe Nest Housing &amp; Support<br />Registered community organisation<br />Your town, UK</p></div></div></div></section>
    <section className="section"><div className="container" style={{ textAlign: 'center' }}><SectionHeading align="center" eyebrow="Start here" title="Let&apos;s talk about what would help." /><ButtonLink href="/contact">Talk to us <Icon name="arrow" size={15} /></ButtonLink></div></section>
  </main>;
}
