import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getScopedIds, requireRole } from '@/lib/auth';
import { audit } from '@/lib/audit';
import { assertReferralTransition } from '@/lib/domain';
export async function POST(request: Request, props: { params: Promise<{ id: string }> }) {
  const params = await props.params;
  try { const user = await requireRole(['super-administrator', 'organisation-administrator', 'service-manager', 'support-lead']); const body = await request.json() as { status?: string; reason?: string; followUpDate?: string }; if (!body.status || !body.reason?.trim()) return NextResponse.json({ error: 'A status and reason are required.' }, { status: 400 }); const serviceIds = getScopedIds(user, 'serviceIds'); const current = await db.referral.findFirst({ where: { id: params.id, organisationId: user.organisationId, ...(serviceIds.length ? { serviceId: { in: serviceIds } } : {}) } }); if (!current) return NextResponse.json({ error: 'Referral not found.' }, { status: 404 }); assertReferralTransition(current.status, body.status); const updated = await db.$transaction(async (tx) => { const row = await tx.referral.update({ where: { id: params.id }, data: { status: body.status, followUpDate: body.followUpDate ? new Date(body.followUpDate) : undefined } }); await tx.referralStatusHistory.create({ data: { referralId: row.id, previous: current.status, next: body.status!, reason: body.reason, changedBy: user.id } }); return row; }); await audit({ organisationId: user.organisationId, actorId: user.id, action: 'REFERRAL_STATUS_CHANGED', resourceType: 'Referral', resourceId: current.id, before: { status: current.status }, after: { status: updated.status, reason: body.reason } }); return NextResponse.json({ ok: true, status: updated.status }); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to update referral.'; const status = message === 'AUTH_REQUIRED' ? 401 : message === 'FORBIDDEN' ? 403 : message.startsWith('Invalid referral') ? 400 : 500; return NextResponse.json({ error: status === 500 ? 'Unable to update referral.' : message }, { status }); }
}
