import type { Metadata } from 'next';
import { getFeaturedVisual, PublicPageHero } from '@/components/PublicUI';

const featuredImage = getFeaturedVisual('privacy');

export const metadata: Metadata = {
  title: 'Privacy notice',
  description: 'How Safe Nest collects, uses, protects, and shares personal information across housing, support, referrals, and this website.',
  openGraph: { images: [{ url: featuredImage.src, alt: featuredImage.alt }] }
};

export default function PrivacyPage() {
  return <main>
    <PublicPageHero eyebrow="Your information" title="Privacy notice" intro="We use information carefully, only for clear purposes, and with appropriate access controls." image={featuredImage} />
    <section className="section"><div className="container content-grid"><article className="prose"><p><strong>Last reviewed: 23 July 2026</strong></p><p>This notice explains how Safe Nest Housing &amp; Support handles personal information when you visit this website, contact us, make a referral, live in one of our homes, or work with us as a partner. We aim to collect only what we need, explain why we need it, and keep it safe.</p><h2>Who is responsible</h2><p>Safe Nest Housing &amp; Support is responsible for the personal information described in this notice. For questions about privacy, data protection, or a request about your information, email <a href="mailto:hello@safenesthousing.org.uk" style={{ color: 'var(--teal-700)', textDecoration: 'underline' }}>hello@safenesthousing.org.uk</a>.</p><h2>Information we may collect</h2><ul><li><strong>Contact details:</strong> name, email address, telephone number, organisation, and how you prefer us to communicate.</li><li><strong>Referral information:</strong> housing situation, support needs, accessibility or communication needs, and information needed to assess safety and suitability.</li><li><strong>Support and housing information:</strong> information needed to provide accommodation, coordinate support, manage a tenancy, respond to safeguarding concerns, and meet contractual or legal duties.</li><li><strong>Website information:</strong> technical information such as browser, device, security logs, and pages requested. See our <a href="/cookies" style={{ color: 'var(--teal-700)', textDecoration: 'underline' }}>cookies page</a>.</li></ul><p>Please do not include more sensitive information than is needed in an ordinary contact message. The referral form explains the information needed for initial triage.</p></article><aside className="info-card"><h3>In an emergency</h3><p>This website and its forms are not emergency services. If someone is in immediate danger, call 999.</p><h3>Domestic-abuse referrals</h3><p>The referral form allows an anonymous identifier where it is not safe to provide identifying details at the first stage.</p><h3>Our promise</h3><p>We do not publish refuge addresses, resident identities, case notes, or safeguarding narratives on public pages.</p></aside></div></section>
    <section className="section section-tint"><div className="container prose" style={{ maxWidth: 900 }}><h2>Why we use information</h2><p>Depending on the situation, we use information to respond to enquiries, assess and manage referrals, provide housing and support, keep people safe, communicate with partners, manage our organisation, improve services, and meet legal, regulatory, funding, insurance, and safeguarding responsibilities.</p><h2>Lawful bases</h2><p>We identify and document the lawful basis for each purpose. Depending on the activity, this may include consent, a contract or steps requested before a contract, a legal obligation, vital interests in an emergency, or a legitimate or recognised legitimate interest such as safeguarding. Where we use special category information, such as health, disability, or safeguarding information, we also identify an additional condition and apply extra safeguards.</p><h2>Sharing information</h2><p>We share information only when it is necessary, proportionate, and lawful. This may include sharing with local authorities, housing teams, health or social-care partners, emergency services, domestic-abuse services, landlords, professional advisers, and trusted technology or communications providers. We do not sell personal information. We will explain sharing where it is safe to do so, although safeguarding or legal duties may limit what we can disclose.</p><h2>Security and access</h2><p>Access is limited by role and need. Sensitive records have additional restrictions, protected documents are stored outside the public web root, and important restricted views and changes are logged. We train staff to handle information carefully and review access when roles change.</p><h2>How long we keep information</h2><p>We keep information only for as long as it is needed for the purpose collected, legal or contractual duties, safeguarding, dispute handling, and accountability. Our retention schedule varies by record type. At the end of the relevant period, information is securely deleted, anonymised, or archived where a lawful reason requires it to be kept.</p><h2>Automated decisions</h2><p>We do not use solely automated decision-making to decide whether someone receives a Safe Nest home or support. Decisions are made by people using the information available and the relevant safeguarding, housing, and service criteria.</p></div></section>
    <section className="section"><div className="container content-grid"><div className="prose"><h2>Your data protection rights</h2><p>You may have the right to ask for access to your information, correction of inaccurate information, erasure in some circumstances, restriction of processing, objection to some processing, and data portability where it applies. If we rely on consent, you can withdraw it, although this will not affect processing already carried out lawfully.</p><p>These rights are not absolute. For example, safeguarding, confidentiality, legal duties, or another person’s rights may mean we cannot provide all information or delete it immediately. We will explain the reason for any restriction.</p></div><div className="info-card"><h3>Make a privacy request</h3><p>Email <a href="mailto:hello@safenesthousing.org.uk" style={{ color: 'var(--teal-700)', textDecoration: 'underline' }}>hello@safenesthousing.org.uk</a> with “Privacy request” in the subject line. Please do not send identity documents or detailed case information until we explain the safest way to verify your request.</p><h3>Raise a concern</h3><p>Tell us first so we can try to resolve it. You can also contact the <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer" style={{ color: 'var(--teal-700)', textDecoration: 'underline' }}>Information Commissioner’s Office</a>.</p></div></div></section>
  </main>;
}
