import { getPublicProperties, getServices, getSiteSettings } from '@/lib/data';
import { ButtonLink, PropertyCard, SectionHeading, ServiceCard, StatsBand, UrgentHelp } from '@/components/PublicUI';
import { Icon } from '@/components/Icons';

export default async function HomePage() {
  const [services, properties, settings] = await Promise.all([getServices(), getPublicProperties(), getSiteSettings()]);
  return <main>
    <section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Housing first · Judgement never</p><h1>{settings['homepage.headline'] ?? 'A safe place to land. The support to move on.'}</h1><p className="hero-copy">Safe Nest provides welcoming homes and practical support for people navigating homelessness, domestic abuse, mental health, and a new start.</p><div className="hero-actions"><ButtonLink href="/referrals">Make a referral <Icon name="arrow" size={15} /></ButtonLink><ButtonLink href="/services" secondary>Explore our services</ButtonLink></div><p className="hero-note"><span />We are here, with you, for what comes next.</p></div><div className="hero-art" aria-label="Abstract image of a calm, welcoming home" role="img" /></div></section>
    <StatsBand settings={settings} />
    <section className="section"><div className="container"><SectionHeading eyebrow="How we help" title="Support that starts with a home." intro="The right home can change what feels possible. Our services are designed around the person, not a label." /><div className="service-grid">{services.slice(0, 6).map((service) => <ServiceCard key={service.slug} service={service} />)}</div></div></section>
    <section className="section section-tint"><div className="container"><SectionHeading eyebrow="A clear next step" title="A referral should feel straightforward." intro="If you are a professional, a family member, or someone looking for support, we will meet you where you are." /><div className="process-grid"><div className="process-step"><h3>Tell us what is happening</h3><p>Share only what you know. Our referral form guides you through the essentials, with a safe route for anonymous domestic-abuse referrals.</p></div><div className="process-step"><h3>We listen and assess</h3><p>A member of our team will acknowledge the referral, understand the situation, and talk through the options with you.</p></div><div className="process-step"><h3>We make a plan together</h3><p>Whether that means a Safe Nest home, a waitlist, or a trusted signpost, you will know what happens next.</p></div></div><div style={{ marginTop: 36 }}><ButtonLink href="/referrals">Start a referral <Icon name="arrow" size={15} /></ButtonLink></div></div></section>
    <section className="quote-section"><div className="container quote-layout"><div className="quote-mark">“</div><div><p className="quote-text">“For the first time in a long time, I could close the door and feel like I was safe.”</p><p className="quote-credit">— Resident, shared with permission</p></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Our homes" title="A place that feels like yours." intro="We share locations at neighbourhood level. Exact refuge addresses are never published; full details are shared with referrers after assessment." /><div className="property-grid">{properties.slice(0, 3).map((property) => <PropertyCard key={property.slug} property={property} />)}</div><div style={{ marginTop: 30 }}><ButtonLink href="/properties" secondary>View all properties <Icon name="arrow" size={15} /></ButtonLink></div></div></section>
    <UrgentHelp />
  </main>;
}
