import { notFound } from 'next/navigation';
import { db } from '@/lib/db';
import { getCrmClients } from '@/lib/data';
import { CrmPageHeader, RestrictedNote, StatusBadge, TableCard } from '@/components/CrmUI';
import { CaseNoteForm } from '@/components/CaseNoteForm';
import { SupportPlanForm } from '@/components/SupportPlanForm';
import { formatDate } from '@/lib/format';
import { canViewRestricted, getCurrentUser } from '@/lib/auth';

export default async function ClientDetailPage(props: { params: Promise<{ id: string }> }) {
  const params = await props.params;
  const user = await getCurrentUser();
  if (!user) notFound();
  let client: any = null;
  try { client = await db.client.findFirst({ where: { id: params.id, organisationId: user.organisationId, ...(!canViewRestricted(user) ? { restricted: false } : {}) }, include: { service: true, placements: { include: { property: true } }, supportPlans: { include: { goals: true, reviews: { orderBy: { reviewDate: 'desc' }, take: 3 } }, orderBy: { createdAt: 'desc' } }, caseNotes: { where: canViewRestricted(user) ? undefined : { restricted: false }, orderBy: { createdAt: 'desc' }, take: 5 }, housingBenefit: true } }); } catch {}
  if (!client) client = (await getCrmClients()).find((item) => item.id === params.id);
  if (!client) notFound();
  const plan = client.supportPlans?.[0] ? { id: client.supportPlans[0].id, reviewDate: client.supportPlans[0].reviewDate } : null;
  return <div className="crm-page"><CrmPageHeader eyebrow={`Client / ${client.reference}`} title={client.displayName} intro={`${client.service?.title ?? 'Unassigned'} · ${client.status}`} action="Add case note" actionHref="#case-note" />{client.restricted && <RestrictedNote />}<div className="metric-grid"><div className="metric-card"><div className="metric-top"><span>Placement</span></div><strong style={{ fontSize: 20 }}>{client.placements?.[0]?.property?.publicName ?? 'Waitlist'}</strong><p>{client.placements?.[0]?.roomId ?? 'No room assigned'}</p></div><div className="metric-card metric-blue"><div className="metric-top"><span>Risk level</span></div><strong style={{ fontSize: 20 }}>{client.riskLevel}</strong><p>Review in supervision</p></div><div className="metric-card metric-gold"><div className="metric-top"><span>Support plan</span></div><strong style={{ fontSize: 20 }}>{plan ? 'Active' : 'Needs setup'}</strong><p>{plan?.reviewDate ? `Review ${formatDate(plan.reviewDate)}` : 'No review date'}</p></div><div className="metric-card metric-teal"><div className="metric-top"><span>Housing Benefit</span></div><strong style={{ fontSize: 20 }}>{client.housingBenefit?.[0]?.status ?? 'Not started'}</strong><p>Finance details are role-limited</p></div></div><div className="crm-panels"><section className="crm-panel"><div className="panel-header"><h2>Overview</h2></div><div className="panel-body"><p style={{ color: 'var(--muted)', fontSize: 12 }}>Communication needs: {client.communicationNeeds ?? 'Not recorded'}</p><p style={{ color: 'var(--muted)', fontSize: 12 }}>Key worker: assigned support lead</p><p style={{ color: 'var(--muted)', fontSize: 12 }}>Record created: {formatDate(client.createdAt)}</p></div></section><section className="crm-panel"><div className="panel-header"><h2>Support plan goals</h2><a href="#support-plan">Add goal →</a></div><div className="panel-body">{client.supportPlans?.[0]?.goals?.length ? client.supportPlans[0].goals.map((goal: any) => <div className="task-item" key={goal.id}><span className="task-check">✓</span><div><strong>{goal.desiredOutcome}</strong><span>{goal.category} · {goal.status}</span></div></div>) : <p className="muted" style={{ fontSize: 12 }}>No goals recorded yet.</p>}</div></section></div><SupportPlanForm clientId={client.id} plan={plan} /><div style={{ marginTop: 18 }}><TableCard title="Recent case notes"><table className="crm-table"><thead><tr><th>Date</th><th>Category</th><th>Outcome</th><th>Access</th></tr></thead><tbody>{client.caseNotes?.length ? client.caseNotes.map((note: any) => <tr key={note.id}><td>{formatDate(note.createdAt)}</td><td>{note.category}</td><td>{note.outcome ?? '—'}</td><td>{note.restricted ? <StatusBadge status="RESTRICTED" tone="warning" /> : <StatusBadge status="PERMITTED" tone="success" />}</td></tr>) : <tr><td colSpan={4}>No case notes recorded.</td></tr>}</tbody></table></TableCard></div><div style={{ marginTop: 18 }}><CaseNoteForm clientId={client.id} /></div></div>;
}
